# Use the official .NET SDK image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TaskDashboardAPI/TaskDashboardAPI.csproj", "TaskDashboardAPI/"]
RUN dotnet restore "TaskDashboardAPI/TaskDashboardAPI.csproj"
COPY . .
WORKDIR "/src/TaskDashboardAPI"
RUN dotnet build "TaskDashboardAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaskDashboardAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskDashboardAPI.dll"]
